name: Build and deploy
on: [push]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ${{ vars.IMAGE_TAG }} .
      - name: Rerun website's Docker container
        env:
          CONTAINER_NAME: ${{ vars.CONATINER_NAME }}
          NETWORK_NAME: ${{ vars.NETWORK_NAME }}
          PORT_PAIR: ${{ vars.PORT_PAIR }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        run: chmod +x ./rerun-container.sh && ./rerun-container.sh
