name: Build and deploy
on: [push]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t maciejpedzi.ch:latest .
      - run: pwd
      - name: Rerun website's Docker container
        run: rerun-container.sh
