name: Build and deploy
on: [push]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t maciejpedzi.ch:latest .
      - name: Rerun website's Docker container
        run: chmod +x ./rerun-container.sh && ./rerun-container.sh ${{ env.CONTAINER_NAME }} ${{ env.PORT_PAIR }} ${{ env.NETWORK_NAME }} ${{ env.IMAGE_TAG }}
